### ISSUE TITLE
An error is generated when creating an island, and the island cannot be created

### ISSUE THREAD

**Issue by hyhaochen233** [OmerBenGera/SuperiorSkyblock2#101]
https://paste.ubuntu.com/p/FdyDp8wrBR/

↑ This is an error that only occurs when the SuperiorSkyblock2 plugin is added

https://paste.ubuntu.com/p/jgsgsw8TmY/

↑ This is an error generated when trying to generate an island

**Comment by OmerBenGera** [comment]
Only spigot jars and it's forks are supported. Weird jars, for example - the one that you're using, aren't supported and will never be.
