### ISSUE TITLE
Respawn in to Void.

### ISSUE THREAD

**Issue by SirCraftypants** [OmerBenGera/SuperiorSkyblock2#103]
Paper 1.16.5
Client Minecraft 1.16.5

I setup my Weather plugin PyroWeatherPro to run extreme weather in my Skyblock world.

If I fall off the island, i respawn as expected back on to the island at the spawn point. 

If I get hit by lightning and killed i respawn in the void and fall to my death.

I also tested the /kill command and that also resulted in me respawning in the void and not on my island.

No Errors or Warns in Console.

**Comment by OmerBenGera** [comment]
Whwn you die, you respawn at the spawn point of the world, not in your island.
