### ISSUE TITLE
Island mob drops not working when upgraded to x2 or x3

### ISSUE THREAD

**Issue by CS223** [OmerBenGera/SuperiorSkyblock2#105]
Okay, so I'm not sure if this has been fixed in a new version as I'm still using SSB-b59 on my server. But when a player upgrades their mob drops on their island to x2 or x3 when a mob is a certain limit the mob stops dropping drops.

I'm using Merged Mobs and Spawners on my server both are on the newest version.
The video below shows the problem (Sorry for the bad video)
https://streamable.com/74w4yi

**Comment by CS223** [comment]
Yeah it works for low stack sizes after it goes past 512 it stops dropping anything at all

**Comment by OmerBenGera** [comment]
Do you have WildStacker installed by any chance?

**Comment by CS223** [comment]
Nah we only use Merged Mobs or Merged Spawners

**Comment by OmerBenGera** [comment]
Mention me on discord, as I need you to send me a copy of MergedMobs

**Comment by CS223** [comment]
Just did my discord is CS | Migo#0195

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue - what version of spigot are you using?

**Comment by CS223** [comment]
Paper spigot 1.8.8

**Comment by OmerBenGera** [comment]
Still works for me - I received x3 times more drops from a x500 skeleton stack when having a x3 multiplier

**Comment by CS223** [comment]
Could you think of a reason why it's doing it on my server then?

**Comment by OmerBenGera** [comment]
> 
> 
> Could you think of a reason why it's doing it on my server then?

Do you have FAWE?

**Comment by CS223** [comment]
Yeah I do

**Comment by OmerBenGera** [comment]
They have items limiter - make sure it's disabled.

**Comment by CS223** [comment]
Yeah, the problem thank you for providing great support!
