### ISSUE TITLE
Somehow I cannot edit the "ISLAND_HELP_FOOTER" and the "ADMIN_HELP_FOOTER"

### ISSUE THREAD

**Issue by SwagPancakes** [OmerBenGera/SuperiorSkyblock2#108]
Somehow I cannot edit the "ISLAND_HELP_FOOTER" and the "ADMIN_HELP_FOOTER" in languages.

Tuinity 1.16.5
Java 11
Superiorskyblock2 v1.5.2 #81

**Comment by OmerBenGera** [comment]
Are you talking about the next page message?

**Comment by OmerBenGera** [comment]
As I can edit the footer without any issues (it's only shown in the latest page)

**Comment by SwagPancakes** [comment]
oh nvm thx it was the next page message
