### ISSUE TITLE
Armor Stands can be interacted with regardless of permissions

### ISSUE THREAD

**Issue by Skizzles** [OmerBenGera/SuperiorSkyblock2#11]
- Plugin Version: SuperiorSkyblock2-b14.jar
- Server Version: 1.16.4 Yatopia
- Errors (Pastebin or ghostbin!): N/A
- Ways to create the issue:
Place down an armor stand on an island and have another user try to grab the items off it.

**Comment by BomBardyGamer** [comment]
Can reproduce, dev build 14, server version 1.12.2

**Comment by OmerBenGera** [comment]
Check out build #15
