### ISSUE TITLE
SUGGESTION: Add hasIsland boolean to check if the player has an island

### ISSUE THREAD

**Issue by SwagPancakes** [OmerBenGera/SuperiorSkyblock2#111]
Add hasIsland boolean to check if the player has an island

**Comment by OmerBenGera** [comment]
Better practice is to do the following:
```
Island island = superiorPlayer.getIsland();
if(island != null){
    // Execute code
}
```
The reason for it is that hasIsland will do this exact same check. However, if you'll need to get the Island variable later, then you're technically calling getIsland twice, which is unnecessary.
I will add this method, however I don't really see a reason for it
