### ISSUE TITLE
Error message with SuperiorSkyblock2 using the SlimeWorldManager addon

### ISSUE THREAD

**Issue by HowAmIFirst** [OmerBenGera/SuperiorSkyblock2#113]
While using the SlimeWorldAddon there is one error that is thrown when the plugin is disabled the error code is here: https://pastebin.com/fVGDSeSd

And another error is thrown when you set "enable_async_world_gen:" to true which throws this error: https://pastebin.com/29JBurie

Even though it's not necessary and the plugin still works without async gen and with the disable error, I would like to improve the efficiency of loading worlds since apparently, async world gen improves world generation significantly. Thanks

**Comment by OmerBenGera** [comment]
This is not related to SSB. Also, the error says that a class is missing from SSB, which makes no sense - download the plugin again.
About the async world gen - make an issue on the addon's page, not here
