### ISSUE TITLE
Can bypass block quests by placing it back down and breaking it

### ISSUE THREAD

**Issue by Nekosity12** [OmerBenGera/SuperiorSkyblock2#114]
Recently added some block quests so as to force players to actually work to finish quests rather than just go to our shop and buy everything however some cheeky players have decided to place down blocks and break them to finish the quest faster. So they can for example use silk touch on coal ore and then place it, break it again with silk touch and it counts towards finishing the quest :/

**Comment by OmerBenGera** [comment]
You can enable the only-natural-blocks option for the mission (just add it to your mission).
This will make it so players must mine naturally spawned blocks (by gens, trees, etc)
