### ISSUE TITLE
Error when creating a new island

### ISSUE THREAD

**Issue by ch1ll1n** [OmerBenGera/SuperiorSkyblock2#115]
Hello,

I am using the latest build of SSB2 with server version 1.12.2. I started getting this error when I tried to create a new island after updating the plugin to the latest build. here: https://paste.ubuntu.com/p/cR57nYhmwS/

**Comment by OmerBenGera** [comment]
What version of SSB are you using? which build exactly.

**Comment by ch1ll1n** [comment]
https://hub.bg-software.com/job/SuperiorSkyblock2/ 87

**Comment by ch1ll1n** [comment]
Hey!! I found the problem :),

If you set the 'bank-worth-rate' setting to 0 in config.yml, you will get this error.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
