### ISSUE TITLE
/is admin setsize/addsize - Needs to be ran twice to take effect.

### ISSUE THREAD

**Issue by JackPlays93** [OmerBenGera/SuperiorSkyblock2#117]
Hello, I am currently running Spigot 1.16.5 with SuperiorSkyblock2-b93 and when using the /is admin setsize and /is admin addsize commands, the commands need to be ran twice in order for the new island size to take effect.

For example, if I have an island size of 50 and want to increase it to 100, I have to run the /is admin setsize 100 command two times before the size actually increases. Same goes for the addsize command.

Thanks,

- Jack

**Comment by OmerBenGera** [comment]
I found out that the actual size is changing, however the visual border isn't.
I am gonna fix it :)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
