### ISSUE TITLE
Vehicle duplication glitch

### ISSUE THREAD

**Issue by Asecta** [OmerBenGera/SuperiorSkyblock2#120]
MC 1.16.5
Version: 1.5.2 (b81 as per jar name)

How to replicate the issue:

Destroying a Minecraft just before it's removed by the island minecart limit causes the item to drop at the same instant as it is put into your inventory. 
I suspect this is easier to reproduce on a server with a large island database as it appears to take advantage of the time period between placing the minecart, and the island database response.

I believe this line is the issue: https://github.com/OmerBenGera/SuperiorSkyblock2/blob/64f268a68eae797cd4eee0b60fdf5de4c8012ec7/src/main/java/com/bgsoftware/superiorskyblock/listeners/UpgradesListener.java#L396

A solution may be to check LivingEntity::isDead on the minecart before returning it to the player? 

Here's a video of the bug in action: 
http://www.pandoaspen.com/fRG7xAYIyi.mp4

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue

**Comment by Asecta** [comment]
Seems fixed in my testing. Great work, thanks :)
