### ISSUE TITLE
Creeper Explosions island setting does not deal damage?

### ISSUE THREAD

**Issue by Skizzles** [OmerBenGera/SuperiorSkyblock2#127]
**Minecraft's Version**
1.16.5

**Plugin's Version**: -
SuperiorSkyblock-b101

**Describe the bug**
Creeper explosions being turned off does not deal damage to the player

**To Reproduce**
Turn off creeper damage
Try to take damage from creeper

**Additional information**
Not sure if this is a bug or if this is intended, I know things like worldguard and other protection type settings usually just stop creeper explosions from breaking blocks and not creeper damage to players so thought I would open an issue about it.

**Comment by OmerBenGera** [comment]
It was suggested to remove the damage from explosions if they are disabled.
Its intended.
