### ISSUE TITLE
Island names that use non-letters cannot be stored normally.

### ISSUE THREAD

**Issue by BingYanchi** [OmerBenGera/SuperiorSkyblock2#131]
**Minecraft's Version**
git-Paper-416 (MC: 1.16.4)

**Plugin's Version**: -
dev-101

**Describe the bug**
The island name will become "??" when stored in the database (I used Chinese)

**To Reproduce**
1. Let Mysql storage support utf-8?

**Additional information**
I don't think it is necessary.

**Comment by OmerBenGera** [comment]
I don't think there's something I can do anything regarding this, as you need set your MySQL to support UTF-8 chars

**Comment by BingYanchi** [comment]
> I don't think there's something I can do anything regarding this, as you need set your MySQL to support UTF-8 chars

I set it up when I created the database, but it still seems like that.

**Comment by OmerBenGera** [comment]
Try this tutorial:
https://www.a2hosting.com/kb/developer-corner/mysql/convert-mysql-database-utf-8

I am not responsible for anything that happens to your DB after doing that.

**Comment by BingYanchi** [comment]
> Try this tutorial:
> https://www.a2hosting.com/kb/developer-corner/mysql/convert-mysql-database-utf-8
> 
> I am not responsible for anything that happens to your DB after doing that.

![image](https://user-images.githubusercontent.com/36477925/112154626-6cabb800-8c1f-11eb-8738-062f50a7c2f6.png)
I do use utf-8, and when I use other plug-ins, this has not happened.

**Comment by BingYanchi** [comment]
> Try this tutorial:
> https://www.a2hosting.com/kb/developer-corner/mysql/convert-mysql-database-utf-8
> 
> I am not responsible for anything that happens to your DB after doing that.

![image](https://user-images.githubusercontent.com/36477925/112154982-cad89b00-8c1f-11eb-86aa-a443f8c4faa5.png)
I do use utf-8, and when I use other plug-ins, this has not happened.

**Comment by OmerBenGera** [comment]
I will check it out 0.0

**Comment by BingYanchi** [comment]
> I will check it out 0.0
> Can you send me the name that you used?

冰糖

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works or not

**Comment by BingYanchi** [comment]
> Check out latest dev build, let me know if it works or not

Yeah, thanks! solved! qwq

**Comment by BingYanchi** [comment]
> Check out latest dev build, let me know if it works or not

Yeah, thanks! solved! qwq
