### ISSUE TITLE
Superior Island Admin permission bug

### ISSUE THREAD

**Issue by Firestone82** [OmerBenGera/SuperiorSkyblock2#134]
**Minecraft's Version**
1.16.5

**Plugin's Version**: -
Latest dev build

**Describe the bug**
Admins cant do their commands, unless they have superior.admin permissions. But that permission adds them access to all admin commands. Tried negating superior.admin.*, and granting them permission one by one. No success.

**Comment by OmerBenGera** [comment]
superior.admin gives access to /is admin, not to all the sub commands.
superior.admin.<sub-command> will give access to a specific sub command.

Therefore, your staff need at least two permissions: one, is superior.admin, and at least one permission to one command - superior.admin.<sub-command>
