### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by RemyyB** [OmerBenGera/SuperiorSkyblock2#19]
Hello,

I'm currently trying to build Superior SkyBlock, I installed the jars from the dependencies with gradle local, only I cannot seem to fix one issue while building with `gradlew shadowJar build`, only to get this for every file:
`C:\Projects\....\SuperiorSkyblock2\src\main\java\com\bgsoftware\superiorskyblock\commands\admin\CmdAdminAdd.java:1: error: cannot access com.bgsoftware.superiorskyblock.commands.admin
package com.bgsoftware.superiorskyblock.commands.admin;
^
  zip END header not found`

I Google'd the hole day but no solution yet..

I cannot seem to find a solution, used Java 8, 11 and 14, switched between multiple gradle versions. Has that issue been here before? Do you maybe have a solution? Any tips or help would be really appriciated! Thank you in advance!!

Remy

**Comment by OmerBenGera** [comment]
Ahm try deleting the archive folder and do that again

**Comment by RemyyB** [comment]
Thanks for your answer, unfortunately I cannot find an archive folder anywhere

**Comment by OmerBenGera** [comment]
Make sure you switch to the dev branch and build that branch

**Comment by RemyyB** [comment]
I already tried that :)

**Comment by OmerBenGera** [comment]
Hmm, try cloning the project again maybe?

**Comment by RemyyB** [comment]
Yep tried that too :P

**Comment by OmerBenGera** [comment]
Weird... was it working before?

**Comment by RemyyB** [comment]
Nope it wasn't, I just cloned the repository and added the local libraries, that's really it unfortunately, I just can't get it to build, thanks for your help

**Comment by OmerBenGera** [comment]
tbh, I have no clue, it's something of gradle... Try deleting its cache and start from scratch

**Comment by OmerBenGera** [comment]
@BomBardyGamer Mind checking this?

**Comment by BomBardyGamer** [comment]
So, these local libraries, have you tried installing them to Maven Local with `mvn install:install-file -Dfile=<path-to-file> -DgroupId=<group-id> -DartifactId=<artifact-id> -Dversion=<version> -Dpackaging=jar` and then adding `mavenLocal()` in `repositories`?

**Comment by BomBardyGamer** [comment]
That's how I usually install local jars to Maven Local, and I never have any issues

**Comment by BomBardyGamer** [comment]
Found a fix: https://stackoverflow.com/questions/52411697/intellij-compilation-error-zip-end-header-not-found
Try and delete the corrupted caches

**Comment by BomBardyGamer** [comment]
From what I have found, that error is only caused by corrupted files

**Comment by RemyyB** [comment]
Thank you for your answer, already found that link and tried all the possible solutions, unfortunately still no success

**Comment by OmerBenGera** [comment]
I recommend trying to remove dependencies until it works

**Comment by RemyyB** [comment]
Yep it was one of the dependencies, thank you very much 👍🏼 :)

Have a nice day and a nice plugin, also there is a bug / weird design that can cause quite big problems because of how this plugin handles island deletions:

If "build outside island" is set to true and if you have max-island-size set to a number that cannot be devided by 16 (chunks) and cannot be devided by 2, if you have this set in the config. If you then delete the island it deletes a part of the chunks of other islands close to it. Maybe you could set the default value to 192 instead of 200 to prevent this from happening :)

Hope this helps

Kind regards,
Remy

**Comment by OmerBenGera** [comment]
Open a new issue regarding the max-island-size thingy
