### ISSUE TITLE
Island effects multiply after restarts

### ISSUE THREAD

**Issue by Chappy202** [OmerBenGera/SuperiorSkyblock2#22]
**Issue Explanation**
When island effects have been applied to a island through `island admin seteffect %player% <effect> 1`, and the server gets restarted - the island effects multiply.

**Example**
Applying HEALTH_BOOST 1 before a restart will give the player 2 extra hearts, after restarting the server, players will have 6 hearts instead of the previous 2

Also, a way to remove effects from island would be great...

**Comment by OmerBenGera** [comment]
Should be fixed in latest build (#29)
