### ISSUE TITLE
Getting All Islands [ API ]

### ISSUE THREAD

**Issue by Drexful** [OmerBenGera/SuperiorSkyblock2#23]
Looking through the source I see you guys have a way to get all of the islands in your main plugin, however that's not accessible in the API or at all. If you could add a List<Island> getAllIslands in your API that would be awesome or if there is another way to do that, please let me know. I need this for a plugin I'm coding.

**Comment by OmerBenGera** [comment]
You can get all the islands using the API - check out the GridManager object, look for getIslands

**Comment by OmerBenGera** [comment]
https://github.com/OmerBenGera/SuperiorSkyblock2/blob/master/API/src/main/java/com/bgsoftware/superiorskyblock/api/handlers/GridManager.java#L250
