### ISSUE TITLE
Eroor with item frame limit

### ISSUE THREAD

**Issue by nivcoo** [OmerBenGera/SuperiorSkyblock2#24]
Hello i can't get placeholder limit of item frame with the placeholder : %superior_island_count_item_frame% maybe an error with the placeholder, i don't try if the limit in the island works. The limit isn't in the /is count or /is amdin count * also

I've this issue in 1.12 and SuperiorSkyblock2-b26 (i thiunk it's new but because i had tried before (2 month ago) and it worked)

**Comment by OmerBenGera** [comment]
Item frame is an entity, and therefore SSB doesn't track it
You can only track blocks, not entities
