### ISSUE TITLE
Multiply drops multiplying held items

### ISSUE THREAD

**Issue by BBSnowIce** [OmerBenGera/SuperiorSkyblock2#25]
**Description of the issue**:
When multiply drops is active, items mobs have in its hands are multiplied, which means if player drops a full shulker box, this is multiplied which is really annoying.

**Expected behabiour**:
Multiply drops does not multiply held Items.

(Maybe this could be revelant but I'm using WildStacker as loottable provider)

**Comment by OmerBenGera** [comment]
How do the entities collect the item? By picking them up or using a custom plugin?

**Comment by BBSnowIce** [comment]
They pick it up on the ground, items are stacked by WildStacker

**Comment by OmerBenGera** [comment]
> They pick it up on the ground, items are stacked by WildStacker

Does it happen without WS installed?

**Comment by BBSnowIce** [comment]
> > They pick it up on the ground, items are stacked by WildStacker
> 
> Does it happen without WS installed?

I just tried and it seems not

**Comment by BBSnowIce** [comment]
*I tried without Item Stacking enabled

**Comment by BBSnowIce** [comment]
And now, I tried some other configurations and with the one shot feature from WildStaker, it still multiplies held items, but with a normal tool, it does not.

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
What's your minecraft version?
What's your WildStacker version?
What's your SuperiorSkyblock version?

**Comment by BBSnowIce** [comment]
WildStacker-b29
SuperiorSkyblock2-b29

And I'm using Paper for 1.16, build 399

The issue seems to appear only with the One Shot feature from WildStacker.

**Comment by OmerBenGera** [comment]
I had one shot enabled and it worked fine for me... Try replicating the issue with only WS and SSB on latest paper build

**Comment by BBSnowIce** [comment]
I tried with only those two plugins and a permission plugin on the latest Paper build, it still does the same, Zombie only has 1 item in his hand (the one that I dropped) and when I kill it, it drops 3

**Comment by OmerBenGera** [comment]
I still can't replicate the issue.
Latest WS, latest SSB and using Paper #414 for 1.16.4

**Comment by OmerBenGera** [comment]
That's exactly how I did it and it worked well without any issues.

**Comment by BBSnowIce** [comment]
Yes I'm using the same build, I'll try to reset bukkit/spigot/paper, WS and SSB config on a test server.

**Comment by BBSnowIce** [comment]
Ok so I tried many things to finally draw these conclusions. As weird as it seems to be, if `next-stack-knockback` is set to false, then, as long as the entity does not take any damage before being one shot, the held Item will be multiplied.

**Comment by BBSnowIce** [comment]
After new tests, it seems to appear on every one shot, not only from the one shot provided by WS, a really powerful sword will do the same.

**Comment by OmerBenGera** [comment]
I managed to replicate the issue, I am gonna check this rn

**Comment by OmerBenGera** [comment]
Build #34 will fix the issue
