### ISSUE TITLE
Error with EpicSpawners

### ISSUE THREAD

**Issue by ch1ll1n** [OmerBenGera/SuperiorSkyblock2#26]
Hello,

My server version is 1.12.2 and I'm using SuperiorSkyblock2 b33 with EpicSpawners version 7.0.2. When I place, break, or combine the spawners in the Island world, I get the following errors.

here: https://paste.ubuntu.com/p/W34yjK38hv/

**Comment by OmerBenGera** [comment]
Looks like EpicSpawners changed their API again in EpicSpawners 7.
Tag me on Discord so I can open a ticket for you as I need a copy of the plugin to add support for it

**Comment by OmerBenGera** [comment]
Check out build #35, let me know if it works

**Comment by ch1ll1n** [comment]
Thanks! It works very well without any errors.

**Comment by OmerBenGera** [comment]
Perfect :D
