### ISSUE TITLE
Updated to Paper 418 SSB2 will not load

### ISSUE THREAD

**Issue by cobrex1** [OmerBenGera/SuperiorSkyblock2#27]
Updated to 418 paper and SSB returns the following errors on chunk callback and the server will not start.

https://pastebin.com/79dZ0Xpg

This is just a snip of all the errors as they are all the same.

Thanks for your help.

**Comment by OmerBenGera** [comment]
Gonna check that out soon.
Any other errors that you receive?

**Comment by cobrex1** [comment]
I'll pastebin the whole startup log for you:

https://pastebin.com/vkBwxrLe

Thanks Omer

**Comment by OmerBenGera** [comment]
Fixed in build #36
