### ISSUE TITLE
FAWE and SSB cause Cobblestone Generators to stop working.

### ISSUE THREAD

**Issue by Skizzles** [OmerBenGera/SuperiorSkyblock2#28]
SuperiorSkyblock-b35
FastAsyncWorldEdit-1.16-549.jar
1.16.4
It seems to only occur when Fast A Sync World edit is installed, As I reinstalled FAWE today I noticed it occurred right after.
I looked into it more on my other modes and removed SSB and the issue goes away, if I uninstall FAWE it also goes away
So seems like a weird reaction between the two.

They just fully stop like this and do not continue.
https://screenshots.skizzles.me/wAnA3/GiMUGOnE80.png

**Comment by OmerBenGera** [comment]
The slimefun machines break the blocks, right?

**Comment by Skizzles** [comment]
This happens with Jets Minions, Slimefun Androids as well. Only reason it does not happen with player is because the player updates the block. So once the blocks are updated then it works.

**Comment by OmerBenGera** [comment]
Well, the plugins that break the blocks **must** update the blocks.
If the blocks aren't updated, then water will not flow, that's how the game works

**Comment by Skizzles** [comment]
Of course, it just seems weird that only the issue occurs with FAWE installed.

**Comment by OmerBenGera** [comment]
well, I don't know. I am not the developer of FAWE, I don't know what they do in their plugin.
I am closing this as it has nothing to do with SSB.
