### ISSUE TITLE
Failed to schedule load callback for chunk

### ISSUE THREAD

**Issue by uLyPANNN** [OmerBenGera/SuperiorSkyblock2#29]
Updated to 1.16.5 and SSB doesn't work (( paper1.16.5 build 434 ))

https://pastebin.com/CPenKHaX  
the server will not start.

**Comment by uLyPANNN** [comment]
https://github.com/OmerBenGera/SuperiorSkyblock2/issues/27 

I solved it, I found this topic 
sorry 🥇

**Comment by OmerBenGera** [comment]
Duplicate of #27
