### ISSUE TITLE
Plugin doesn't working

### ISSUE THREAD

**Issue by NieToNieJa** [OmerBenGera/SuperiorSkyblock2#31]
I wrote about it on discord but nobody managed to deal with this problem and they sent me here, maybe you can help me.
Plugin makes so much errors (if i deleted the plugin when the server start working normal)
Error link: https://pastebin.pl/view/d6f3674a

**Comment by NieToNieJa** [comment]
Can u help me plz

**Comment by OmerBenGera** [comment]
The pastebin cannot be loaded. Upload it to another service

**Comment by NieToNieJa** [comment]
https://pastecode.io/s/sJL1UkM7fR

**Comment by OmerBenGera** [comment]
It means that the biome is null, as I said already.
What version of SSB and MC are you using?

**Comment by NieToNieJa** [comment]
Latest SSB - SuperiorSkyblock2-b36
Minecraft - 1.16.4
Spigot - 1.16.4

**Comment by OmerBenGera** [comment]
I am checking this rn

**Comment by NieToNieJa** [comment]
ok ♥

**Comment by OmerBenGera** [comment]
Check out build #37
