### ISSUE TITLE
interactables.yml BUG

### ISSUE THREAD

**Issue by voicestory776** [OmerBenGera/SuperiorSkyblock2#33]
SSB Version 1.5.2
Server Version 1.12.2

I entered DIAMOND_BLOCK' in the interactables.yml file.
If there is only one block, it is protected, but if two or more overlap, it is not protected.
Not affected by'Interact' in /is permissions, but affected by'Breack'.

Player Role = Coop
Interact = Member
Breack = Coop

Can't you break the other blocks and protect the overlapping diamond blocks?

##
                                                  
               SuperiorSkyblock 2                
                Developed by Ome_R                

 A list of interactable blocks.
 Only interactable blocks & stacked blocks will be blocked from being interacted.
interactables:
- 'DIAMOND_BLOCK'
##

**Comment by OmerBenGera** [comment]
What do you mean by "overlapping diamond blocks"?

**Comment by voicestory776** [comment]
![image](https://user-images.githubusercontent.com/52654457/105170243-fe377480-5b5f-11eb-9854-0af9d19b69ec.png)

stacked blocks = DIAMOND BLOCK

**Comment by OmerBenGera** [comment]
Stacked barrels are safe and cannot be interacted by players that don't have access to break the blocks, and there's no need to add them to the interactables list

**Comment by voicestory776** [comment]
Is there any way to protect certain stacked blocks?
