### ISSUE TITLE
Bug save missions

### ISSUE THREAD

**Issue by LeRoiDamien** [OmerBenGera/SuperiorSkyblock2#37]
Good evening again ^^
When my server crashes I get the following message.
thus when restarting the server the missions in progress are reset

sorry to bother you again

[Server thread/ERROR]: Nag author: 'Ome_R' of 'SuperiorSkyblock2' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.

**Comment by OmerBenGera** [comment]
You can ignore the message.
Why does your server crash?

**Comment by OmerBenGera** [comment]
Check out build #41, I added save task for missions data, so they will be saved every 5 minutes.

**Comment by LeRoiDamien** [comment]
Thank you very much sorry for the inconvenience ^^

**Comment by OmerBenGera** [comment]
I am closing this now :)
Hopefully it will not rollback too much when your server crashes now
