### ISSUE TITLE
Crashes server on 1.16

### ISSUE THREAD

**Issue by KickSquareMC** [OmerBenGera/SuperiorSkyblock2#38]
Hi, I installed the plugin and it crashes the server whenever I restart.

Here are the errors in console: https://pastebin.com/780Neth5

**Comment by OmerBenGera** [comment]
Already fixed in latest dev builds

**Comment by KickSquareMC** [comment]
Hi, I've done that (tried b41 and b42) and the server doesn't crash on startup anymore. The plugin shows up in /pl as working. However, when I do any commands (/is, /island, etc.) it says unknown command. Are there any dependencies now or something?

**Comment by OmerBenGera** [comment]
> Hi, I've done that (tried b41 and b42) and the server doesn't crash on startup anymore. The plugin shows up in /pl as working. However, when I do any commands (/is, /island, etc.) it says unknown command. Are there any dependencies now or something?

Maybe you havent completed the first installation guide. You get a message when you join the server - read it and go through the pages

**Comment by KickSquareMC** [comment]
Hi, thanks for the reply. I do not know what message you mean. Do you have a link to the installation guide?

**Comment by OmerBenGera** [comment]
> 
> 
> Hi, thanks for the reply. I do not know what message you mean. Do you have a link to the installation guide?

When you join the server, you get a message if you're opped. simple.

**Comment by KickSquareMC** [comment]
Oh ok. I never use op, that's why. Thanks!

**Comment by OmerBenGera** [comment]
Let me know if you still don't receive it :)

**Comment by KickSquareMC** [comment]
Hi,

That worked, superiorskyblock now works completely, thanks!

I know this is only for superiorskyblock but I'm having the same issue with wildstacker, I'm opped but there's no tutorial or anything

**Comment by OmerBenGera** [comment]
WildStacker has no tutorial, it's only implemented in SuperiorSkyblock

**Comment by KickSquareMC** [comment]
Do you have any idea why it isn't working? It already generated all the files

**Comment by OmerBenGera** [comment]
> 
> 
> Do you have any idea why it isn't working? It already generated all the files

Ask in the discord server for help

**Comment by KickSquareMC** [comment]
Alright
