### ISSUE TITLE
error items biome

### ISSUE THREAD

**Issue by LeRoiDamien** [OmerBenGera/SuperiorSkyblock2#39]
Hello I have this problem in the log while in game the menu works very well I even change the items with stone I have the same error

http://pastebin.fr/81708

**Comment by OmerBenGera** [comment]
Fix the items in the biome menu to meet your server version. This is not an issue with the plugin.

**Comment by LeRoiDamien** [comment]
even with the empty biome file I still have the concerns ...
https://prnt.sc/xjphdu

**Comment by OmerBenGera** [comment]
> 
> 
> even with the empty biome file I still have the concerns ...
> https://prnt.sc/xjphdu

what's your minecraft version

**Comment by LeRoiDamien** [comment]
1.16.5  but it does it to me since 1.16

**Comment by OmerBenGera** [comment]
show me the new error with that menu file

**Comment by LeRoiDamien** [comment]
http://pastebin.fr/81763

**Comment by OmerBenGera** [comment]
You probably don't save or upload the file if it reads items that aren't in your file

**Comment by LeRoiDamien** [comment]
Even with the basic config, in games I have all the items displayed in the biome gui ^^

**Comment by OmerBenGera** [comment]
Then you don't change the menu file correctly.

**Comment by LeRoiDamien** [comment]
I do not modify the file I only translate

**Comment by OmerBenGera** [comment]
You're not editing the file, you keep the same file with invalid items in the menus folder.

**Comment by OmerBenGera** [comment]
Hmm, I might have found the broken menu - it might be the top islands menu

**Comment by LeRoiDamien** [comment]
So yes it is the top island menu that gives this error :) thank you anyway :)

**Comment by OmerBenGera** [comment]
> 
> 
> So yes it is the top island menu that gives this error :) thank you anyway :)

Sorry about that - I am gonna fix it rn

**Comment by LeRoiDamien** [comment]
no problem :)
