### ISSUE TITLE
Nether portal not working

### ISSUE THREAD

**Issue by J4im3x0** [OmerBenGera/SuperiorSkyblock2#40]
Hello,

Nether portal is not teleporting to nether island (in gamemode 0), but as I tried, works on gamemode 1,
there is a video that shows the problem https://www.youtube.com/watch?v=yGc-_YWmuMs

SuperiorSkyBlock2 version: 1.5.2
Server version: tacospigot 1.8.8

**Comment by OmerBenGera** [comment]
Do you have the nether world disabled in the server.properties?

**Comment by J4im3x0** [comment]
> Do you have the nether world disabled in the server.properties?

Yes, because if I enable the default world will have a nether.

**Comment by OmerBenGera** [comment]
Check out build #45, let me know if it works for you

**Comment by J4im3x0** [comment]
> Check out build #45, let me know if it works for you

Did not work :(

**Comment by OmerBenGera** [comment]
Weird, I can't replicate the issue.
When going through a portal in Survival, it works fine for me :(

Are you able to replicate the issue on localhost?

**Comment by J4im3x0** [comment]
> Weird, I can't replicate the issue.
> When going through a portal in Survival, it works fine for me :(
> 
> Are you able to replicate the issue on localhost?

I want to apologize, not sure what not worked, but as I tested now, it's working (with build #45 was fixed).
How do you manage portal teletransportation? I am pretty sure that I feel portal slow, maybe for that today I thought that were not working.

**Comment by OmerBenGera** [comment]
> > Weird, I can't replicate the issue.
> > When going through a portal in Survival, it works fine for me :(
> > Are you able to replicate the issue on localhost?
> 
> I want to apologize, not sure what not worked, but as I tested now, it's working (with build #45 was fixed).
> How do you manage portal teletransportation? I am pretty sure that I feel portal slow, maybe for that today I thought that were not working.

When you teleport for the first time, the world is loaded and the schematic is pasted, so it might feel slow a bit. I am using the PlayerTeleportEvent so there isnt really an unusual delay :)
