### ISSUE TITLE
tools lag spike

### ISSUE THREAD

**Issue by LeRoiDamien** [OmerBenGera/SuperiorSkyblock2#42]
Hello, I currently have spike lag when a lot of people do the fields with the harvester here is the spark link
Version b7

https://spark.lucko.me/#jkfZXngLF9

**Comment by LeRoiDamien** [comment]
ok i will do that in the meantime

**Comment by OmerBenGera** [comment]
Hey, can you test build #46 and having the bank worth rate enabled?

**Comment by LeRoiDamien** [comment]
I tested here is the result 
https://spark.lucko.me/#Z8NlWW4VxQ

**Comment by OmerBenGera** [comment]
Rip, no difference.
I'll see how it can be optimized even more

**Comment by LeRoiDamien** [comment]
Ok ^^

**Comment by OmerBenGera** [comment]
@LeRoiDamien check out latest dev build, hopefully it will be better 0.0

**Comment by LeRoiDamien** [comment]
I just put it on, I'll keep you posted

**Comment by OmerBenGera** [comment]
My bad, the update hasn't been pushed yet.
There are issues on my end, I will let you know once it's pushed and released.

**Comment by OmerBenGera** [comment]
Check out build 87

**Comment by OmerBenGera** [comment]
@LeRoiDamien Have you tried it?

**Comment by LeRoiDamien** [comment]
Yes I have more problem for the moment

**Comment by OmerBenGera** [comment]
Great, I am closing this for now.
If the issue occurs again, make sure you reopen the issue

**Comment by LeRoiDamien** [comment]
Good evening, I have the problem again I updated this morning
SuperiorSkyblock2-b108
WildTools-b11

https://spark.lucko.me/98JAC3WSEn

**Comment by OmerBenGera** [comment]
I can't see lag from SuperiorSkyblock - you just have general lag on your server.
Getting entities's locations is causing lag, which makes no sense - or in other words, your server is just lagging due to other events causing everything to lag.
