### ISSUE TITLE
Is chat not working

### ISSUE THREAD

**Issue by J4im3x0** [OmerBenGera/SuperiorSkyblock2#43]
Using `/is chat` to toggle island chat does not works, just sends the message of enabled/disabled but the channel still being default server chat. 
![image](https://user-images.githubusercontent.com/36940599/105646204-6b5b4a80-5e7d-11eb-807c-67edfe78223d.png)
Just works `/is chat <message>` 
![image](https://user-images.githubusercontent.com/36940599/105646219-86c65580-5e7d-11eb-8cd0-6133d874271b.png)

SuperiorSkyBlock version: 1.5.2
Server version: tacospigot 1.8.8

**Comment by OmerBenGera** [comment]
It works fine for me, might be due to a custom chat plugin that you use

**Comment by J4im3x0** [comment]
> It works fine for me, might be due to a custom chat plugin that you use

Yes, you are right. Apparently is incompatible with ezChat https://www.spigotmc.org/resources/ezchat-next-generation-chat.75048/updates

**Comment by OmerBenGera** [comment]
Change the chat priority in their config to NORMAL/HIGH/HIGHEST, and it will be fixed.
