### ISSUE TITLE
only-show-if-required-completed doesn't check for required-checks placeholders

### ISSUE THREAD

**Issue by alexnpark** [OmerBenGera/SuperiorSkyblock2#45]
**Description:**
In the missions.yml, the option `only-show-if-required-completed` should hide the GUI item unless the `required-checks:` and `required-missions:` are "completed," however, the option does not hide GUI items if `required-checks:` is not "completed." Instead, it is always shown in the GUI regardless if the required-checks requirements are not met.

**Example:**
This applecollector mission is intended to be completely hidden from the GUI unless the player has more than $2000. To check for this, I used `required-checks:` to check if the %vault_eco_balance% was more than $2000. Only after that expression is true, should the mission appear in the GUI. 

``` applecollector:
    mission-file: ItemsMissions
    island: false
    auto-reward: false
    disband-reset: true
    only-show-if-required-completed: true
    required-checks:
      - '%vault_eco_balance% > 2000'
    required-items:
      '1':
        types:
          - 'APPLE'
        amount: 10
    reset-after-finish: false 
```
The `only-show-if-required-completed` option works fine if I'm only checking for `required-missions`, but not for `required-checks`. The required-checks _does_ work fine for completion (If I have more than $2000 and the 10 apples, I can complete the mission) but just doesn't hide it properly.

**Spigot Version:** 1.16.4, 1.16.5 (Tested with Spigot, Paper, and Tuinity)
**Plugin Version:**. SuperiorSkyblock2-b41

There are no logs/errors in console.

**Comment by OmerBenGera** [comment]
Fixed in build 51 :)

**Comment by alexnpark** [comment]
Perfect! Thank you :)
