### ISSUE TITLE
bank limit exceeded message

### ISSUE THREAD

**Issue by ch1ll1n** [OmerBenGera/SuperiorSkyblock2#46]
Hello,

I'm using the latest build of the plugin. When a player tries to deposit more than the bank money limit I have set, the plugin doesn't send any warning messages, and this makes the bank limit incomprehensible for players.
No logs/errors in the console.

**Comment by OmerBenGera** [comment]
Like they can't deposit due to the limit, but they don't get a message neither?

**Comment by ch1ll1n** [comment]
Yes, literally

**Comment by OmerBenGera** [comment]
Hey, I've just tried to replicate the issue and I receive a message.
Maybe the message is empty in the lang file? look for `BANK_LIMIT_EXCEED` in the lang files

**Comment by ch1ll1n** [comment]
Uhm..  this is strange. There are no errors in the language file. First, I updated the bank-limit to 50000000 from the config.yml file. After making the necessary reloads, I opened the bank in the game and wrote 50000001 in the chat with the option to set a special amount to deposit. I could not deposit any money in the bank and there was no message in the chat. When I clicked on the buttons to deposit all or half of the money in my account, I did not receive any message or deposit money into the bank.

**Comment by OmerBenGera** [comment]
I'll check it via the menu, as I used /is deposit

**Comment by OmerBenGera** [comment]
So I checked the menu, and there is a sound when you fail to deposit the money.
There are no messages for failure actions in the menu

**Comment by ch1ll1n** [comment]
Can you do this for the menu? Players may not hear the game audio or may be turned off.

**Comment by OmerBenGera** [comment]
I added it in latest dev build :)
Closing this for now
