### ISSUE TITLE
Spawn egg animals

### ISSUE THREAD

**Issue by LeRoiDamien** [OmerBenGera/SuperiorSkyblock2#47]
Hello, I have a problem with mob eggs

I currently have all the permissions on the island there are no animals so the limit is 128. no animal eggs works with a / summon it works without forgetting that the eggs of aggressive mobs works

**Comment by OmerBenGera** [comment]
I don't understand what the issue is

**Comment by LeRoiDamien** [comment]
the problem is that we cannot put animals on certain islands so when I deactivate the SuperiorSkyblock plugin I can

**Comment by OmerBenGera** [comment]
You might not have the permission to spawn animals / animals spawning is disabled on the island.
If you mean vanilla spawning, the issue might be that the island is too small, as animals don't spawn near players

**Comment by LeRoiDamien** [comment]
Yes the animal spawn works very well but the problem comes from the eggs

**Comment by OmerBenGera** [comment]
Only animals from eggs do not spawn? What about spawners?

**Comment by LeRoiDamien** [comment]
just the animal eggs, the spawner works very well

**Comment by OmerBenGera** [comment]
Are you sure it's related to SSB? Mind taking a video of the issue?

**Comment by LeRoiDamien** [comment]
I just noticed that in the settings the eggs work with 'Animal spawner' I'm sorry

**Comment by OmerBenGera** [comment]
Great :)
I am closing this for now
