### ISSUE TITLE
Issue with EpicSpawners' custom item spawners and island values menu(/is values)

### ISSUE THREAD

**Issue by ch1ll1n** [OmerBenGera/SuperiorSkyblock2#49]
Hello,

I am using EpicSpawners 7.0.5 and the latest build of SSB2. I created some item spawners with EpicSpawners. When I put these spawners that I created while on my island, they appear on the menu, and when I break these spawners without pressing any keys(like shift for break combined spawners in EpicSpawners), they disappear from the menu. BUT if I break the spawners I placed by pressing the shift key, it does not disappear from the menu and causes a major bug for island worth/level. Also, the spawners I created do not appear in the menu when I place them only once, I have to combine 2 or more spawners to appear in the menu. No logs/errors in the console. I've also tried the things I've done with animal/mob spawners, but no such error occurred.

**Comment by OmerBenGera** [comment]
I don't think custom item spawners are supported... I'll check that out tho

**Comment by ch1ll1n** [comment]
Thanks, I need that so much

**Comment by OmerBenGera** [comment]
Mind tagging me on the discord server? I'll need a copy of EpicSpawners 7 and a quick tutorial on how to create these type of spawners

**Comment by ch1ll1n** [comment]
Hello again, I tested the last version but 1 bug still persists. First, put 1 custom item spawner on the floor and check it in the /is value menu. You will see that the amount of spawner is not increased there. Next, put another next to your spawner and combine the two. This time you will see the spawner amount increased by 1 in the menu.

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by ch1ll1n** [comment]
nice
