### ISSUE TITLE
Crop multiplier system not working

### ISSUE THREAD

**Issue by MedicOP** [OmerBenGera/SuperiorSkyblock2#5]
Using a Paper build with this commit breaks the crop multiplier system. The custom crop growth tile entity is not ticked at all. Crops are growing at vanilla speeds even though islands have 40x multiplier.
https://github.com/PaperMC/Paper/commit/2c37d1077f0e245b93801beba6b79cf762bd2cef

Downgrading to a build without the above change makes the multipliers work again.

**Comment by OmerBenGera** [comment]
Hey, [dev build #7](https://hub.bg-software.com/job/SuperiorSkyblock2/7/) should fix it. Let me know if it works for you

**Comment by OmerBenGera** [comment]
I am closing this for now, if it still happens let me know

**Comment by MedicOP** [comment]
Still happening

**Comment by OmerBenGera** [comment]
> 
> 
> Updated to latest Paper today, still happening with dev build #7

I've just checked it on latest version of Paper & latest dev build and it works just fine.

**Comment by MedicOP** [comment]
ok latest dev build works, dev build 7 not
