### ISSUE TITLE
Using special characters when creating a warp(!, ? etc.)

### ISSUE THREAD

**Issue by ch1ll1n** [OmerBenGera/SuperiorSkyblock2#50]
Hello,

I am using the latest build of SSB2. When I use special characters in the warp name while creating a new warp, warp is saved anonymously and is not deleted in any way. When I restart the server, the warp name changes to 1 automatically. In short, special characters should not be used when creating a warp.

**Comment by OmerBenGera** [comment]
How do you create the warps, as it shouldn't be possible to create warp names that don't meet the following regex: [a-zA-z0-9_]

**Comment by ch1ll1n** [comment]
"/is warp !", "/is warp ?&/+!" etc. etc.

Also, I can create with "/is warp !asd" and it only appears as asd in the menu.

**Comment by OmerBenGera** [comment]
How did you **create** the warp?
Also, it's not a valid command - /is warp [warp-name] is not a thing, only /is warp [player/island]

**Comment by ch1ll1n** [comment]
I am sorry, I edited the reply just now xD

**Comment by OmerBenGera** [comment]
> 
> 
> "/is setwarp !", "/is setwarp ?&/+!" etc. etc.
> 
> Also, I can create with "/is setwarp !asd" and it only appears as asd in the menu.

that's sounds like an intended behavior - /is setwarp !asd will create the warp as "asd".
Also, let me get this clear - when using only illegal chars, it just creates a warp with an empty name, correct? And that's obvious a bug.

**Comment by ch1ll1n** [comment]
> Also, let me get this clear - when using only illegal chars, it just creates a warp with an empty name, correct? And that's obvious a bug.

yeap

**Comment by OmerBenGera** [comment]
Check out build #47

**Comment by ch1ll1n** [comment]
fixed, working very well. thank you
