### ISSUE TITLE
Member to Visitor issue ?

### ISSUE THREAD

**Issue by nivcoo** [OmerBenGera/SuperiorSkyblock2#55]
Hello, i don't know how to reproduce this bug (I use the SuperiorSkyblock2-b54.jar in 1.12.2). So, my player has island with team leader, but after his login today he stay in island but like visitor, i seen the logs and i see this https://pics.edensky.fr/2021-02/01/12-14_WRBb.png but before that i have saved the db and look the old db : https://pics.edensky.fr/2021-02/01/12-15_X0bv.png , the UUID is the same and the teamleader also. It's the first time that i see this message. thx

**Comment by nivcoo** [comment]
So as visitor he can't break/place block and can't leave island, to fix the issue teamleader has to change role of this player

**Comment by OmerBenGera** [comment]
You have a plugin or something that changes UUIDs of players - this is not supported and can lead to unexpected behaviors.

**Comment by nivcoo** [comment]
I use Online mode of minecraft in my server, you can look the uuid in namemc...

**Comment by nivcoo** [comment]
If you look the plugin change uuid with the same uuid

**Comment by OmerBenGera** [comment]
Well, the uuid was definitely changed somehow.
There's nothing to do with that, you can set him as leader or reset his data.

**Comment by nivcoo** [comment]
"Well, the uuid was definitely changed somehow."

So, i have backup of yesterday i will send you the saved uuid : 9d1a66bf-b42a-48b7-ac63-7ba967e0870e like this screen https://pics.edensky.fr/2021-02/01/12-15_X0bv.png and you can look my other screen https://pics.edensky.fr/2021-02/01/12-14_WRBb.png with the uuid 9d1a66bf-b42a-48b7-ac63-7ba967e0870e , so the uuid is 100% the same, SuperiorSky try to change uuid with the same uuid.
This is the first time that this happens to me, as I said I managed to solve his problem but I don't want it to happen to other person when there is potentially a real problem

**Comment by OmerBenGera** [comment]
There's no issue. The UUID was changed or there was another member with the same name that joined but different UUID.
