### ISSUE TITLE
/is missions event error if the player doesn't have an island

### ISSUE THREAD

**Issue by ch1ll1n** [OmerBenGera/SuperiorSkyblock2#56]
Hello,

I am using the latest build of SSB2. "Could not pass event InventoryClickEvent" error appears when a player clicks on the island missions section in the /is missions menu while not having an island. That's all ^^

**Comment by OmerBenGera** [comment]
Are you sure you're using latest dev build?
As I remember fixing a similar issue

**Comment by OmerBenGera** [comment]
I just tried to replicate the issue with the latest dev build and I don't get any errors

**Comment by ch1ll1n** [comment]
https://paste.ubuntu.com/p/SHbhvBmCBP/

**Comment by OmerBenGera** [comment]
Where did you click to get this error?

**Comment by OmerBenGera** [comment]
I'll check it out again

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
