### ISSUE TITLE
admins cannot teleport to locked islands 

### ISSUE THREAD

**Issue by literallyEllie** [OmerBenGera/SuperiorSkyblock2#58]
https://github.com/OmerBenGera/SuperiorSkyblock2/blob/625829a8d5028cd74d51698681c198156e159133/src/main/java/com/bgsoftware/superiorskyblock/listeners/CustomEventsListener.java#L343

allowed "superior.admin.teleport" to bypass the island privilge check if locked.

**Comment by OmerBenGera** [comment]
Enable bypass mode or have the permission superior.admin.bypass.close_bypass to bypass locked islands
