### ISSUE TITLE
Random /is home location if home location is being blocked

### ISSUE THREAD

**Issue by jaegyuch** [OmerBenGera/SuperiorSkyblock2#59]
I covered up my /is home location with a cobble generator, and it seems like once that spawn location is being interrupted it uses a random location to teleport me back to the island, regardless of if it's land or not. Could you perhaps make it so that players are teleported on top of the object, rather than some random place?

In the picture below, I am just flying, there are no blocks underneath me and that is where I got teleported to when I used /is home.

![2021-02-06_10 07 21](https://user-images.githubusercontent.com/45920595/107122062-9e311580-6863-11eb-8d03-6b1d866dc43a.png)

**Comment by OmerBenGera** [comment]
That's intended.
When the home location is not safe, the plugin looks for another location to set your home at.
When a new location is looked for, then it checks for a block to be below, so you don't need to be worried about that.
