### ISSUE TITLE
/island admin add not working 

### ISSUE THREAD

**Issue by CS223** [OmerBenGera/SuperiorSkyblock2#61]
My server version: https://i.imgur.com/dqJwWAi.png

All my plugins are up to date.

The first issue is that /Island admin add does not work it does not add the player to the Island that we want and gives a random reason why it won't work any error in the console too but here is a video of it not working.
https://streamable.com/6aflly

**Comment by OmerBenGera** [comment]
Open 3 different issues for 3 different bug reports, and give them proper titles.
Keep this issue for the first issue and change the title please.

**Comment by CS223** [comment]
Done! Good luck fixing thme

**Comment by OmerBenGera** [comment]
Hey, check out dev build 58, let me know if it fixes the issue

**Comment by CS223** [comment]
Just tested it and it works good job! You can close this
