### ISSUE TITLE
 MergedSpawner/SilkSpawners Console spam error does not count them in Island top

### ISSUE THREAD

**Issue by CS223** [OmerBenGera/SuperiorSkyblock2#62]
This error has something to do with MergedSpawner/SilkSpawners I think it gets spammed in my console every few seconds + none of my spawners get counted at all in /Island top (https://ghostbin.com/paste/ZZQEp)

**Comment by OmerBenGera** [comment]
Hey, the error seems to be cut. Mind taking another paste of the error?

**Comment by CS223** [comment]
Here you go https://ghostbin.com/paste/0pF8j

**Comment by OmerBenGera** [comment]
It's still cut. Can you send me the entire logs file?

**Comment by CS223** [comment]
Yeah here you go https://ghostbin.com/paste/Vg7P9

**Comment by OmerBenGera** [comment]
Update MergedSpawner to latest version and it will be fixed :)

**Comment by CS223** [comment]
I'm on the latest version of MergedSpawners

**Comment by OmerBenGera** [comment]
> 
> 
> I'm on the latest version of MergedSpawners

What version are you on?

**Comment by CS223** [comment]
The version on the server is 12.4.0 Which is the latest version of MergedSpawners

**Comment by OmerBenGera** [comment]
MergedSpawner v12.4.0 is a really old version and it's not latest.
Latest versions of MS are posted on Polymart, you should check it out.

**Comment by OmerBenGera** [comment]
I now remember some complains about customers on Spigot can't get access to the new versions and they must re-purchase the plugin. Let me know if that's the case, and I'll do my best to add support for the latest version on Spigot as well, so you are not forced to re-purchase it.

**Comment by CS223** [comment]
I have messaged the Dev of MergedSpawner to see if I can get the plugin on Polymart or If I need to buy it again as I never knew that he had stopped updating it on Spigot for some reason, so I will let you know soon!

**Comment by CS223** [comment]
Hey just to update you on this yeah even if you previously owned you have to pay a fee of $2.15 as it's a "New plugin" even tho it does everything the same. But I have bought it and now I am on version 13.7.1 which is the newest version and /is top still won't count any of the spawners and no errors in the console too

**Comment by OmerBenGera** [comment]
What's your discord? I'll open a ticket for you on the discord server and we'll talk there

**Comment by CS223** [comment]
Here is my discord CS | Migo#0195

**Comment by OmerBenGera** [comment]
I've just tested MergedSpawners with SuperiorSkyblock and it seems to work just fine.
Mind taking a video of the issue?

**Comment by CS223** [comment]
Yeah here you go: https://streamable.com/je1pf8

**Comment by OmerBenGera** [comment]
Check out in /is blocks if they are shown there or not.

**Comment by CS223** [comment]
It does not show up in /Is Blocks

**Comment by OmerBenGera** [comment]
I understand. Do you have worth or levels set to the spawners?

**Comment by CS223** [comment]
Wait a question first any way I can just set the level for all of the mob spawners instead of setting them individually? But I do have levels for them set + I'm using ShopGUI for the buy worths

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by CS223** [comment]
No update still won't work honestly I'm not even sure what to do anymore as I have a server release this Firday and I really ned /is top to work

**Comment by OmerBenGera** [comment]
Try it on a server with only SSB & MergedSpawner installed.

**Comment by CS223** [comment]
Okay so now it's fixed after I just reset my config yml never really changed anything in it in the first place but now it works.

**Comment by OmerBenGera** [comment]
Great, might have been your spawners-provider section was set to something else :)
