### ISSUE TITLE
EpicSpawners and place spawners mission

### ISSUE THREAD

**Issue by ch1ll1n** [OmerBenGera/SuperiorSkyblock2#65]
Hello,

I am using the latest build of SSB2 and EpicSpawners 7.0.5. I created a mission called "Place 20 spawners." I've made all the settings, everything works fine, but there is a problem. When players place spawners without combining(epicspawners feature) them, they are counted for the mission progress, but if they put spawners next to each other and combine them, the spawners they placed is not counted for the progress.

Also, I have an extra question. I have an extra question. If players constantly put in and break 1 spawners, the mission is counted for progress. In short, the task "Place 20 spawners." can be completed with only 1 spawner. Is there any way to fix this?

**Comment by OmerBenGera** [comment]
The blocks mission doesn't support EpicSpawners merging. You can create your own mission that supports it.
