### ISSUE TITLE
Problem with fire_spread

### ISSUE THREAD

**Issue by TheMartyCZ** [OmerBenGera/SuperiorSkyblock2#66]
Hello, I have a problem with fire_spread, which is located in /is settings. When I turn it off, the crafting table will still burn, but it will not be destroyed.

Information: 
ss2: #58
paper: sspigot 1.16.3

**Comment by OmerBenGera** [comment]
Are you sure it's related to SSB..?
If the fire spread is enabled, then fire can break any block...

**Comment by TheMartyCZ** [comment]
Sorry, should be written "turn off". I corrected it.

**Comment by OmerBenGera** [comment]
When fire spread is set to false, then fire will not burn blocks neither.

**Comment by TheMartyCZ** [comment]
But they still start to burn.

**Comment by OmerBenGera** [comment]
Mind taking a short clip? I don't think I quite understand

**Comment by TheMartyCZ** [comment]
![image](https://user-images.githubusercontent.com/45405349/107896393-6d717000-6f36-11eb-881e-f27337d59945.png)

It's hard to make a video. Burning is very accidental.

**Comment by OmerBenGera** [comment]
If you have fire spread disabled, then blocks will not burn

**Comment by TheMartyCZ** [comment]
That's what I'm forbidden to do, but it's still burning.

**Comment by OmerBenGera** [comment]
It gets one fire probably as the event isn't called, however the block isn't burnt completely, no?

**Comment by TheMartyCZ** [comment]
The object starts to burn but is not destroyed.

**Comment by OmerBenGera** [comment]
> 
> 
> The object starts to burn but is not destroyed.

yeah, that's "intended". I'll see if it can be fixed, not sure about that tho

**Comment by TheMartyCZ** [comment]
Okay, thank you!

**Comment by OmerBenGera** [comment]
Keeping this opened for now

**Comment by OmerBenGera** [comment]
Latest dev build should fix the issue :)
