### ISSUE TITLE
SuperiorSkyblock stops working with a 278.892 line error log output

### ISSUE THREAD

**Issue by DKPeak** [OmerBenGera/SuperiorSkyblock2#67]
Hi,

First **/island top** stopped working, and about 2 minutes after superiorskyblock stopped working at all. I checked the logs, and it had over 300.000 lines. We restartet the server and now we cant start the server again.

Heres the 278.892 line error:
https://discord.com/channels/554276823010246687/554282577322704896/809499273317842984

The error after we startede up again:
https://pastebin.com/9Ck4XJkZ

- DKPeak

**Comment by DKPeak** [comment]
So, theres a update
After the server couldn't start again, we got to work.
First of we downloaded the datebase and opened it with DBBrowser SQLite, with checked the logs and saw that the error started when loading islands. It said something about an infinite number. We found out that one island had 373523.750 in their bank. We deleted their total bank, uploadede the database and boom it worked. It took us about 1 hour and 40 minutes to fixes, but now its fixed. We disabled island bank with skript and removed the menu.

I hope this somehow helps

**Comment by DKPeak** [comment]
Now the server crashed again. Heres the log hole log: https://we.tl/t-6xOz6VwnR7
It startet at: 17:04:09

Forgotten information
![image](https://user-images.githubusercontent.com/64193972/107792489-8242dd80-6d55-11eb-9ff3-073adb3bc690.png)

**Comment by OmerBenGera** [comment]
Looks like on of your islands has a corrupted worth value, which breaks the plugin from loading.
Fix it manually and everything will be fine.

Btw, I don't know what "Heres the 278.892 line error" means, you sent a link to a discord channel and not to a direct attachment.

**Comment by DKPeak** [comment]
Dont know how, but i have send the wrong link. The 278.892 line error is here: https://we.tl/t-BBjzUfTukj (WeTransfer)

Since you closed it, does that mean we just have to live with a daily crash and island bank not working? We aren't able to find out what causes the crashes of server, we just fixed it once.

**Comment by OmerBenGera** [comment]
I told you how to fix it already
