### ISSUE TITLE
Custom Block Break Mission

### ISSUE THREAD

**Issue by ch1ll1n** [OmerBenGera/SuperiorSkyblock2#68]
Hello,

I am using the latest build of SSB2 with server version 1.12.2. I want to create a mission called "Break 64 Obsidian". For this, I changed the default woodcutter mission given in the missions.yml file. I deleted the logs in the required blocks section and added the obsidian. But when I break obsidian on the server, the mission progress doesn't count. But if I remove the obsidian and write log, it counts as mission progress. I also tried the IDs of the blocks, but I could not solve the problem. When I tried different blocks other than obsidian it didn't work either.

**Comment by OmerBenGera** [comment]
Show me your mission setup please

**Comment by ch1ll1n** [comment]
https://paste.ubuntu.com/p/dxpFYHRzmg/

**Comment by OmerBenGera** [comment]
I copy-pasted the exact same mission to my localhost, and it works just fine for me.
Maybe there's a plugin that conflict with it?

**Comment by ch1ll1n** [comment]
Hmm, are you using SSB2 with server version 1.12.2? I added another 5-6 blocks besides obsidian, they didn't work either. If everything is the same, I may need to do a detailed look at the plugins.

**Comment by OmerBenGera** [comment]
I used it on 1.16.5, however it shouldn't matter.
Did you try to break obsidian on your island and it didn't count?

**Comment by ch1ll1n** [comment]
The mission must be complete in a world except of the Islands. When I break logs, the mission progresses, but when I try with other blocks, it doesn't.

**Comment by OmerBenGera** [comment]
All missions only work inside the island worlds.

**Comment by ch1ll1n** [comment]
Umm, when I tried the woodcutter mission, it was working in all worlds.

**Comment by OmerBenGera** [comment]
I don't know why it doesn't work for you, but I can't replicate the issue using your exact same missions setup.
I am closing this issue for now
