### ISSUE TITLE
Spawner Boost + Wildstacker possible not working

### ISSUE THREAD

**Issue by MythricHD** [OmerBenGera/SuperiorSkyblock2#70]
Just tried testing out the spawner boost in superiorskyblock.

Here is an image showing that I actually have the spawner boost: https://i.riftmc.co/wisTJocXXt.png

Here is the wildstacker info item, not looking any faster after the boost: https://i.riftmc.co/43Cq5BUKbT.png

Running 1.5.2 (might be a build, honestly not sure how to figure out the b# if so)

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by MythricHD** [comment]
Didn't seem to change the rates after testing with spawner boost 100

**Comment by OmerBenGera** [comment]
It worked fine for me, so it's probably something on your end.
Try it on a server with only WildStacker and SuperiorSkyblock installed.

**Comment by MythricHD** [comment]
So i tried on a new server on the latest build of ss2 and WS but still when a change the rates using a command like 
/island admin setspawnerrates MythricHD 10000
I don't see any considerable change in how fast the mobs are spawning and the spawn delay inside of the wildstacker GUI doesn't change from the default. I tried with placing spawners after I add the boost still nothing. Not sure what could be going on here. When it worked for you did it make the wildstacker clock in the GUI faster or something like that?

**Comment by OmerBenGera** [comment]
10000 sounds like a really large boost that will not work, of course.
Try a reasonable boost, like 10, and check if the delay for next spawn is between 20 and 80 ticks (You can see it using WildStacker)

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by MythricHD** [comment]
Sorry ill take a look this week

**Comment by MythricHD** [comment]
It looks like it works on the latest builds of SSB and WS. Thanks for your patience!

**Comment by OmerBenGera** [comment]
Great :D
