### ISSUE TITLE
setspawnerrates command + EpicSpawners

### ISSUE THREAD

**Issue by ch1ll1n** [OmerBenGera/SuperiorSkyblock2#71]
Hello,

I am using the latest build of SSB2 and EpicSpawners 7.0.5 with server version 1.12.2. I am trying to increase spawner rates with command "/is admin setspawnerrates" on Islands, but It doesn't work(I tried 10, 100, 1000).

**Comment by OmerBenGera** [comment]
EpicSpawners might not work with vanilla setDelay methods.
Ask their team what can be done regarding this.

**Comment by ch1ll1n** [comment]
What exactly should I ask them?

**Comment by OmerBenGera** [comment]
> 
> 
> What exactly should I ask them?

Ask them how to alter spawner delays using other plugins, as the plugin already alters the vanilla's spawn delay and it doesn't work with their plugin

**Comment by ch1ll1n** [comment]
Their support team are horrible, I can't receive any feedbacks for questions. closing this
