### ISSUE TITLE
Bug ore generator

### ISSUE THREAD

**Issue by TheMartyCZ** [OmerBenGera/SuperiorSkyblock2#72]
Hello, sometimes the lava doesn't want to melt and make a cobble. Where to look for a problem? The problem also occurs when you kick with a pickaxe.

https://user-images.githubusercontent.com/45405349/108042476-1e176680-7040-11eb-8cbf-311b1d2f56cb.mp4

SSSPIGOT: 1.16.3
SB2: #60

**Comment by OmerBenGera** [comment]
This is because the minions don't cause physics update to the block they break.
Nothing to do on SSB's end. Also, SSB doesn't handle water / lava flows, so it's obviously an issue with the minions plugin.

**Comment by TheMartyCZ** [comment]
https://user-images.githubusercontent.com/45405349/108195305-e11ea300-7117-11eb-9794-fcf3f0a86de8.mp4

**Comment by OmerBenGera** [comment]
Try uninstalling FAWE if you have it, I heard that it can interface with it.
Again, nothing to do with SuperiorSkyblock.

**Comment by TheMartyCZ** [comment]
@OmerBenGera 
Without WE, the worldguard will not work, without the worldguard I will not protect the spawn because the spawn protection that SSB2 has cannot prohibit the hatching of hens' eggs.
