### ISSUE TITLE
Chat Color in Island chat, Bank withdraw, Warp name.

### ISSUE THREAD

**Issue by Firestone82** [OmerBenGera/SuperiorSkyblock2#75]
Hi, I have few chat color issues in superior.

When players are trying to type into island chat, there is &Code signs in front of it. Can I somehow start parsing it or removing?

When player are trying to withdraw money from bank, its saying to them that its wrong number, because its added &Code sign in front of it.

When players are trying to rename a warp. Its added &Code in front of it, but in this way. It removes & sign, But lefts code char after that symbol. 

I can fix it by my self forking SSB2, but its better if you fix it for future updates. Could you please look into it?

**Comment by OmerBenGera** [comment]
You cant have colored warp names, lets start with that.
About the island chat - same thing, colored chat isnt supported.
About the withdraw - they shouldnt add color codes to their values...

I dont understand what the issue, the players just dont nees to use color codes...

**Comment by Firestone82** [comment]
My chat plugin automaticky add & codes to chat. Your plugin somehow takes the format before its turned into colors or IDK. 
This is caused by chat insertion.

**Comment by Firestone82** [comment]
I have gone through your code and like about bank withdraw. You are lising for chat event. So simply if you could strip colored chars if they are not enabled would fix all.

About withdraw just striping & codes

In island chat, striping it out again if its not supported.

Thats the ways I would do. Hope its enough informations

**Comment by OmerBenGera** [comment]
Your plugin should not add &, but the actual color char instead.
However, it should add it in higher priorities, and make sure you don't add them if the event is cancelled.
Nothing to do on SSB's end, just fix your colors plugin

**Comment by Firestone82** [comment]
I have the priority on lowest because of one plugin. What im doing is added & chars then using ChatColor to translate it

**Comment by OmerBenGera** [comment]
You shouldn't use lowest, sorry. That's an incorrect usage of the plugin.

**Comment by Firestone82** [comment]
About that canceling.. I already have `if (event.isCancelled()) return;` at start. :/ Will tryng doing it on normal priority.

**Comment by OmerBenGera** [comment]
It's cool that you have it, but when you use the LOWEST priority it's useless, as your code runs before almost all the other checks.
You should use NORMAL or HIGH for that.

**Comment by Firestone82** [comment]
I know I should, but its because of that one plugin :/ So I will have to make for of ssb to make it work?

**Comment by OmerBenGera** [comment]
I'd recommend to fix that one plugin that causing trouble and not change all the other plugins to work with it.

**Comment by Firestone82** [comment]
Its this plugin.. https://github.com/BingoRufus/ChatItemDisplay 
Its using events on lowest.. So I have to modify chat before it, otherwise it will not work..
Thanks for help, will try to fork that ChatItemDisplay plugin and change priorities..
