### ISSUE TITLE
Issue with the option "build-outside-island"

### ISSUE THREAD

**Issue by RemyyB** [OmerBenGera/SuperiorSkyblock2#8]
Hey! Thank you for open sourcing this plugin 🥇, I really like the plugin and especially the customizability from it. However I have a small issue:

**What I'm trying to achieve** is let players build to each other's islands, so they can connect islands.

**What I tried**
When I have the option build-outside-island OFF and I create an island, I have a world border.
However when I set the option ON and want to create an island, I won't get a world border.

**What I would like**
I would like to have an option or something to have the build-outside-island set to true and allow world borders to be enabled.

OR BETTER, have an option to set the distance between islands (and not having it so the island size is 3x bigger then the max size), so this won't even be neccessary :)

Hope this is clear enough, thank you in advance!

Remy

**Comment by OmerBenGera** [comment]
The option 'build-outside-island' gives the ability to build outside of your island, aka no borders or anything like that.
That's not an issue - if you want this to be changed, join the discord and create a suggestion :)
