### ISSUE TITLE
After the island owner (or the player with the permission to set the island) goes offline for a period of time, the permissions granted to visitors will be reset.

### ISSUE THREAD

**Issue by BingYanchi** [OmerBenGera/SuperiorSkyblock2#83]
No error was reported, but such a problem occurred every time.
When the island is restarted, the island permissions will be reset. This phenomenon did not cause any errors. I am also not sure if it is my problem. Other data are normal.

Paper 1.16.4

**Comment by OmerBenGera** [comment]
If you reset your island, of course the permissions are reset...
That's intended.

**Comment by BingYanchi** [comment]
> If you reset your island, of course the permissions are reset...
> That's intended.

It appeared after restarting the server.

**Comment by OmerBenGera** [comment]
Ah I understand.
I'll check it out I guess.
Which permissions are you talking about exactly? roles permissions or player permissions?

**Comment by BingYanchi** [comment]
> Ah I understand.
> I'll check it out I guess.
> Which permissions are you talking about exactly? roles permissions or player permissions?

island permissions, It is stored in the mysql database like other island information.

**Comment by OmerBenGera** [comment]
> 
> 
> > Ah I understand.
> > I'll check it out I guess.
> > Which permissions are you talking about exactly? roles permissions or player permissions?
> 
> island permissions, It is stored in the mysql database like other island information.

You can assign permissions for roles and players. Which permissions reset?

**Comment by BingYanchi** [comment]
> > 
> > 
> > > Ah I understand.
> > > I'll check it out I guess.
> > > Which permissions are you talking about exactly? roles permissions or player permissions?
> > 
> > island permissions, It is stored in the mysql database like other island information.
> 
> You can assign permissions for roles and players. Which permissions reset?

roles permissions

**Comment by OmerBenGera** [comment]
I couldn't replicate the issue. I tried SQLite tho.
Mind testing it yourself in SQLite?

**Comment by BingYanchi** [comment]
> 我无法复制该问题。我尝试了SQLite。
> 介意在SQLite中自己测试吗？



> I couldn't replicate the issue. I tried SQLite tho.
> Mind testing it yourself in SQLite?

Sorry, my previous statement was wrong.

I asked other players again, and their answer to me was this:

When a player with management permissions (island permissions) goes offline for a period of time (not to reconnect immediately after going offline), the permissions that appear will be reset. (They opened up some permissions to visitors, but after they were offline for a while, the island permissions were reset)

Maybe this is a bug, maybe not related to Mysql or SQLite?

Note: This situation can be reproduced without restarting the server

**Comment by BingYanchi** [comment]
In short, the approximate recurrence conditions are as follows:

(Not sure necessary) Open some permissions in Island permissions to visitors.

The island owner/player who has control of Island permissions is offline for a period of time (currently there is no sufficient evidence to prove if there are island members who do not have this control permission online will it avoid resetting)

**Comment by BingYanchi** [comment]
Correction: Only when certain permissions in Island permissions are set to visitors, these adjusted permissions will be reset. If the permission is not given to the guest, it will not be reset.

**Comment by OmerBenGera** [comment]
I tried replicating the issue but couldn't. Also it doesn't make a lot of sense why it would reset after you leave the server...

**Comment by BingYanchi** [comment]
> I tried replicating the issue but couldn't. Also it doesn't make a lot of sense why it would reset after you leave the server...

I will try to reproduce it again, which will cause you trouble. qwq

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by BingYanchi** [comment]
> Any news regarding this?

This phenomenon does occur on my server. I am still trying to reproduce this problem on a clean server. I'm sorry to keep you waiting.

I would like to ask another question. Does this plugin have a protection mechanism similar to "After island members are offline for a period of time, the permissions open to visitors will be reset to the default state"?

Because this problem only appears in the permissions granted to visitors, so I have this suspicion. I'm still trying to reproduce the problems mentioned before. As soon as there is progress, I will give feedback and I will do it as soon as possible.

**Comment by BingYanchi** [comment]
I tried to reproduce it and it succeeded.

I found that this bug only appears in Mysql, not SQLite. (I tested it, it is true)

Steps:
1. Enable Mysql in config.yml
2. Set island options (/is permissions)
3. The island members are offline for a while (I’m five minutes, but I’m not sure it’s necessary)
4. Restart the server (required)
5. Re-enter the server and you will find that all permissions have been reset.

**Comment by OmerBenGera** [comment]
I couldn't replicate the issue... Tried with MySQL and every step you said, and couldn't replicate it.

**Comment by BingYanchi** [comment]
> I couldn't replicate the issue... Tried with MySQL and every step you said, and couldn't replicate it.

But I really tested it, or I will record a video to demonstrate it later.

**Comment by OmerBenGera** [comment]
> 
> 
> > I couldn't replicate the issue... Tried with MySQL and every step you said, and couldn't replicate it.
> 
> But I really tested it, or I will record a video to demonstrate it later.

There's no reason for it to occur (especially if it's only in MySQL, as there's no difference between MySQL and SQLite)

**Comment by BingYanchi** [comment]
> > > I couldn't replicate the issue... Tried with MySQL and every step you said, and couldn't replicate it.
> > 
> > 
> > But I really tested it, or I will record a video to demonstrate it later.
> 
> There's no reason for it to occur (especially if it's only in MySQL, as there's no difference between MySQL and SQLite)

I am using MySQL 5.5.62. I tested Mysql and SQLite separately, but it is true that only Mysql has this situation.

**Comment by OmerBenGera** [comment]
maybe, idk.

**Comment by BingYanchi** [comment]
> maybe, idk.

So what is the recommended Mysql version, I want to try again.

**Comment by OmerBenGera** [comment]
> 
> 
> > maybe, idk.
> 
> So what is the recommended Mysql version, I want to try again.

I really don't know, there's no recommended version. All versions work.

**Comment by BingYanchi** [comment]
> > > maybe, idk.
> > 
> > 
> > So what is the recommended Mysql version, I want to try again.
> 
> I really don't know, there's no recommended version. All versions work.

https://www.youtube.com/watch?v=1rDo0qVmvwc

This is the situation I encountered and I recorded the whole process.

In addition, I have verified that this problem does not occur in SQLite.

**Comment by OmerBenGera** [comment]
I think the issue is because of the name of guest role. From the video, it seems like it's replaced with ????, which means you have it with non UTF-8 chars.

**Comment by BingYanchi** [comment]
> I think the issue is because of the name of guest role. From the video, it seems like it's replaced with ????, which means you have it with non UTF-8 chars.

I used "游客" and "合作者", but this should belong to UTF-8 encoding.

**Comment by OmerBenGera** [comment]
The issue is because of the non alphabetic chars.
Just to make sure, let's try and change the role names to default, and let me know if it still occurs.
If it doesn't, then we know what the issue is and I will fix it

**Comment by BingYanchi** [comment]
> The issue is because of the non alphabetic chars.
> Just to make sure, let's try and change the role names to default, and let me know if it still occurs.
> If it doesn't, then we know what the issue is and I will fix it

Yes, I changed the name in config.yml to English and everything is normal. Is it possible to use the default name when storing data?

**Comment by OmerBenGera** [comment]
> 
> 
> > The issue is because of the non alphabetic chars.
> > Just to make sure, let's try and change the role names to default, and let me know if it still occurs.
> > If it doesn't, then we know what the issue is and I will fix it
> 
> Yes, I changed the name in config.yml to English and everything is normal. Is it possible to use the default name when storing data?

I will fix it, it's considered as a bug. It should use role ids instead to not have such issues.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue

**Comment by OmerBenGera** [comment]
I just noticed that the recent dev builds failed. I fixed it now, so check out build 101

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by BingYanchi** [comment]
> Any news regarding this?

After my test, it succeeded, thanks!
