### ISSUE TITLE
End Portal Teleport Loop

### ISSUE THREAD

**Issue by ilker** [OmerBenGera/SuperiorSkyblock2#84]
When the end portal is made to the spawn point of the island, the player loops and the server crashes.
1- I made an end portal to the island's spawn point.
2- I teleported to the island of End.
3- I returned to the normal island with the "/is" command and I was born inside the portal.
4- I got into a cycle. I teleported to the island of End and then kicked back to the normal island. I got into an endless loop like this. After a while, the server crashed.

**Comment by OmerBenGera** [comment]
Weird, there should be a teleport cooldown of like 10 seconds so you can instantly teleport.
I will check it out, might be due to a recent patch for the end/nether worlds being disabled but still functioning for islands.

**Comment by OmerBenGera** [comment]
Hey, this should be fixed in latest dev build.
Let me know if it still occurs.

**Comment by ilker** [comment]
In patch 68, "/is chest" was not used. I was getting an error. Has that
problem been fixed?

Ome_R <notifications@github.com>, 21 Şub 2021 Paz, 23:51 tarihinde şunu
yazdı:

**Comment by OmerBenGera** [comment]
I don't know what you talk about.
Build 69 will fix the portals issue.

**Comment by ilker** [comment]
The portal problem has been resolved. Also works is chest.

İlker Taçyıldız <tacyildizilker@gmail.com>, 21 Şub 2021 Paz, 23:55
tarihinde şunu yazdı:

**Comment by OmerBenGera** [comment]
Great :)
I am closing this for now
