### ISSUE TITLE
Generator rates

### ISSUE THREAD

**Issue by adviis** [OmerBenGera/SuperiorSkyblock2#85]
Hey, I have a little problem.

It seems to me that this is a bug, when configuring the drop, when I give a chance of e.g. 0.8%, nothing falls off the stone at all (it works from a chance of 1.0%, can you add the possibility of a drop lower than the 1% chance?).

Thanks for reading have a nice day.

**Comment by OmerBenGera** [comment]
You must use integers - decimals will not work.
If you want to set a 0.8 chance, set the chance for your material to 8, and the other materials should have a chance of 992.
The chance percentage per material is calculated as the chance divided by the total chances. So if you set the chance to 8, it's percentage will be 8 / (8 + 992) = 8/1000 = 0.8%
