### ISSUE TITLE
Island Bank - Refunded money

### ISSUE THREAD

**Issue by tptuaasn** [OmerBenGera/SuperiorSkyblock2#87]
This function does not work. I tried restarting, disband the island. Create islands, deposit money. And delete the island again .... And yes, no amount is refunded ...

Turn off server, re-enable ... Delete island ..

Try it again and again and still it is.

Minecraft Version: 1.16.5
Plugin: SuperiorSkyblock2-b68

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
