### ISSUE TITLE
Fire spread changes affect ignition of blocks in all cases

### ISSUE THREAD

**Issue by Skizzles** [OmerBenGera/SuperiorSkyblock2#88]
https://github.com/OmerBenGera/SuperiorSkyblock2/commit/5177c9314edb0f76104a4cfcaafad582b1274449

Causes players to not be able to ignite blocks at all.

Usually fire spread means that a player could ignite a single block but the fire would not spread to any surrounding blocks.

In this case no one can ignite a block at all.
https://youtu.be/CWqpzbQAjXc

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
