### ISSUE TITLE
There is an error with the maximum number of TRIPWIRE_HOOK

### ISSUE THREAD

**Issue by Lode-D** [OmerBenGera/SuperiorSkyblock2#90]
https://cdn.discordapp.com/attachments/554282577322704896/814596557478297630/unknown.png
^ setting of TRIPWIRE_HOOK ^

https://cdn.discordapp.com/attachments/554282577322704896/814598556924510289/2021_02_26_05_41_05_367.mp4
^ error is limit of TRIPWIRE_HOOK ^

**Comment by OmerBenGera** [comment]
Upload the video to youtube or any other online streaming service.

**Comment by Lode-D** [comment]
https://www.youtube.com/watch?v=OGlSCdgKBHA <<< here

**Comment by OmerBenGera** [comment]
/is level will fix it as a temp fix.
I will see if I can fix it with a solution that will not cause lag

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build, let me know if it works for you as well :)
