### ISSUE TITLE
Setcropgrowth 

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [OmerBenGera/SuperiorSkyblock2#95]
setcropgrowth doesn't seem to be increasing the growth rate of potatoes or carrots but works with wheat

1.16
Build 71

**Comment by OmerBenGera** [comment]
Are they whitelisted in the crops list in the config?

**Comment by YouSeeMeRunning2** [comment]
crops-to-grow:
- CACTUS
- SUGAR_CANE_BLOCK
- SUGAR_CANE
- MELON_STEM
- ATTACHED_MELON_STEM
- RED_MUSHROOM
- BROWN_MUSHROOM
- PUMPKIN_STEM
- ATTACHED_PUMPKIN_STEM
- VINE
- COCOA
- SAPLING
- DARK_OAK_SAPLING
- JUNGLE_SAPLING
- OAK_SAPLING
- ACACIA_SAPLING
- BIRCH_SAPLING
- SPRUCE_SAPLING
- CROPS
- WHEAT
- CARROT

**Comment by YouSeeMeRunning2** [comment]
Sorry had to add "POTATOES"
