### ISSUE TITLE
Minor Menu Issues

### ISSUE THREAD

**Issue by Firestone82** [OmerBenGera/SuperiorSkyblock2#96]
In Permissions menu, there is not working "back" button and also, has-permission.sound is not playing, only no-permission does.
'-> When I add there normal sounds for the rest of buttons its not working too. 

In biomes menu, there is working "back" button but when I add it there, there is no icon for it, when I click at that slot, it closes normally, but icon wont show.

Same as above does in Island TOP menu.

In island warps ('warps.yml') back button is not working. Clicks makes sound, but wont close or go back.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know what still occurs, as I couldn't replicate the back button not working in the permissions menu or the warps menu. The other issues should be fixed

**Comment by Firestone82** [comment]
Hi, some bugs keep happening.

In /is warp back button not working.. Maybe Im bumb.. Config file for testing.. https://pastebin.com/tv5URY76
In /is permissions, back button is not working and it wont make extra sound on non permission icon. Permission icon now click and make sounds but otherones not. Config file.. https://pastebin.com/gZ1hTAKt

Others are fixed, thanks.

**Comment by OmerBenGera** [comment]
In the permissions menu, you didn't set any back buttons or any sounds category.

**Comment by OmerBenGera** [comment]
Same in the warps menu, you didn't set any back buttons

**Comment by Firestone82** [comment]
Oh. It didnt update.

**Comment by Firestone82** [comment]
Oh wait. If I set it.. It removes.

**Comment by Firestone82** [comment]
In permissions.yml. I do 
`
back: '#'
slots: '@'
previous-page: <
current-page: '*'
next-page: '>'
`
Then /is admin reload
After that it gets back to
`

slots: '@'
previous-page: <
current-page: '*'
next-page: '>'
`

**Comment by Firestone82** [comment]
Same for sounds section, i can add it, but it gets removed.

**Comment by OmerBenGera** [comment]
I understand. Does it happen only with the permissions menu?

**Comment by Firestone82** [comment]
Same in warps menu it just removes after reload.

**Comment by Firestone82** [comment]
I dont know how to show you.. Just I add that section "back: true" in permissions.yml or warps.yml save it.. And after I do /is admin reload, that config gets updated and that section I have added is gone. So thats the problem why its not working I guess. You mayve have in plugin that it works, but it keeps disappearing from menu.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works with this jar

**Comment by Firestone82** [comment]
Nope, again it gets removed. When you are trying it, Its not working for you?

**Comment by OmerBenGera** [comment]
The issue seemed to be with the implementation of the CommentedConfiguration (a class to support comments for configs).
Try latest dev build, should be fixed now.

**Comment by Firestone82** [comment]
Works, thanks
