### ISSUE TITLE
Sponge AutoStack

### ISSUE THREAD

**Issue by nivcoo** [OmerBenGera/SuperiorSkyblock2#97]
Hello look the video https://pics.edensky.fr/2021-03/02/17-40_pFpf.mp4 (It's a previous fixed bug but I have the worries again). You have to place AutoStack of sponge, and place water.

**Comment by OmerBenGera** [comment]
The issue is that it turned into wet sponge, right?

**Comment by nivcoo** [comment]
Yes sorry i didn't explain the issue

**Comment by OmerBenGera** [comment]
I will check it out. Weird, I remember fixing it a while ago for you, I might have removed the patch for it by a mistake.

**Comment by OmerBenGera** [comment]
@nivcoo Please upload your config content to pastebin, I might know what the issue is.

**Comment by OmerBenGera** [comment]
Hey, I pushed an update that should fix the issue (if you use paper above 1.13. If not, enable physics listener in the config)
