### ISSUE TITLE
End portal generated not opening

### ISSUE THREAD

**Issue by piet0906** [OmerBenGera/SuperiorSkyblock2#98]
When trying to use a end portal in the schematic it places them correct rotated but when you fill them up with eye of ender it doesn't open you have to replace every single one of the end portal frames before it opens

**Comment by OmerBenGera** [comment]
Do you have the portal lit up in the schematic?

**Comment by piet0906** [comment]
No just a few ender eyes in it already but not all because we want players to get the eyes themselfes

**Comment by OmerBenGera** [comment]
I'll check that out, might be an issue with how end portals are saved in schematics.
What's your server version?

**Comment by OmerBenGera** [comment]
I couldn't seem to replicate the issue on 1.16 or 1.12.
Make sure you use latest dev build, and re-create the schematics in the latest dev build using the built in system of the plugin
